stripe:
  secretKey: sk_test_51QxRppQO5yqa0GmivRNnYh2cWbtVfYdpSYmPA7kMZk6Z3fF8CTBr2ZiWjTqchUQTn4Aj7M53riSILDcBwoiWBdxz00StnmJ1BF
  publishableKey: pk_test_51QxRppQO5yqa0GmiXZY8cMFo3DaeHWj3ugOuERGOLpVCxaG9v8bvL4W7NszY6akbGFHQyTuhqVlXHum1ZpmjE0z700g4YIBKqN
